apiVersion: v1
kind: Service
metadata:
  name: controller-manager-metrics-service
  labels:
    {{- include "oam-core-resources.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    {{- include "oam-core-resources.labels" . | nindent 4 }}