{{- if and .Release.Namespace (.Values.createNamespace | default false) -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "oam-core-resources.labels" . | nindent 4 }}
{{- end -}}