apiVersion: v1
kind: Service
metadata:
  name: {{ include "oam-core-resources.fullname" . }}
  labels:
    {{- include "oam-core-resources.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9443
      protocol: TCP
      name: http
  selector:
    {{- include "oam-core-resources.selectorLabels" . | nindent 4 }}