{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oam-core-resources.serviceAccountName" . }}
  labels:
    {{ include "oam-core-resources.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
