# permissions to do viewer containerizedworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerizedworkload-viewer-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - containerizedworkloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - containerizedworkloads/status
  verbs:
  - get
