# permissions to do edit containerizedworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerizedworkload-editor-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - containerizedworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - containerizedworkloads/status
  verbs:
  - get
  - patch
  - update
