# permissions to do edit manualscalertraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manualscalertrait-editor-role
rules:
- apiGroups:
  - core.oam.dev
  resources:
  - manualscalertraits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - manualscalertraits/status
  verbs:
  - get
  - patch
  - update
