apiVersion: core.oam.dev/v1alpha2
kind: ContainerizedWorkload
metadata:
  name: example-containerized-workload
spec:
  containers:
    - name: my-nginx
      image: nginx
      resources:
        cpu:
          required: "1.0"
        memory:
          required: "200Mi"
      ports:
        - containerPort: 4848
          name: example
          protocol: "TCP"
      env:
        - name: WORDPRESS_DB_PASSWORD
          value: ""